# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ODEInt')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ODEInt')
    _ODEInt = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ODEInt', [dirname(__file__)])
        except ImportError:
            import _ODEInt
            return _ODEInt
        try:
            _mod = imp.load_module('_ODEInt', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ODEInt = swig_import_helper()
    del swig_import_helper
else:
    import _ODEInt
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ODEInt.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _ODEInt.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ODEInt.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ODEInt.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ODEInt.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ODEInt.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ODEInt.SwigPyIterator_copy(self)

    def next(self):
        return _ODEInt.SwigPyIterator_next(self)

    def __next__(self):
        return _ODEInt.SwigPyIterator___next__(self)

    def previous(self):
        return _ODEInt.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ODEInt.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ODEInt.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ODEInt.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ODEInt.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ODEInt.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ODEInt.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ODEInt.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _ODEInt.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class LineInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LineInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LineInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _ODEInt.LineInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ODEInt.LineInt___nonzero__(self)

    def __bool__(self):
        return _ODEInt.LineInt___bool__(self)

    def __len__(self):
        return _ODEInt.LineInt___len__(self)

    def __getslice__(self, i, j):
        return _ODEInt.LineInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ODEInt.LineInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ODEInt.LineInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ODEInt.LineInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ODEInt.LineInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ODEInt.LineInt___setitem__(self, *args)

    def pop(self):
        return _ODEInt.LineInt_pop(self)

    def append(self, x):
        return _ODEInt.LineInt_append(self, x)

    def empty(self):
        return _ODEInt.LineInt_empty(self)

    def size(self):
        return _ODEInt.LineInt_size(self)

    def swap(self, v):
        return _ODEInt.LineInt_swap(self, v)

    def begin(self):
        return _ODEInt.LineInt_begin(self)

    def end(self):
        return _ODEInt.LineInt_end(self)

    def rbegin(self):
        return _ODEInt.LineInt_rbegin(self)

    def rend(self):
        return _ODEInt.LineInt_rend(self)

    def clear(self):
        return _ODEInt.LineInt_clear(self)

    def get_allocator(self):
        return _ODEInt.LineInt_get_allocator(self)

    def pop_back(self):
        return _ODEInt.LineInt_pop_back(self)

    def erase(self, *args):
        return _ODEInt.LineInt_erase(self, *args)

    def __init__(self, *args):
        this = _ODEInt.new_LineInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _ODEInt.LineInt_push_back(self, x)

    def front(self):
        return _ODEInt.LineInt_front(self)

    def back(self):
        return _ODEInt.LineInt_back(self)

    def assign(self, n, x):
        return _ODEInt.LineInt_assign(self, n, x)

    def resize(self, *args):
        return _ODEInt.LineInt_resize(self, *args)

    def insert(self, *args):
        return _ODEInt.LineInt_insert(self, *args)

    def reserve(self, n):
        return _ODEInt.LineInt_reserve(self, n)

    def capacity(self):
        return _ODEInt.LineInt_capacity(self)
    __swig_destroy__ = _ODEInt.delete_LineInt
    __del__ = lambda self: None
LineInt_swigregister = _ODEInt.LineInt_swigregister
LineInt_swigregister(LineInt)

class LineDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LineDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LineDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _ODEInt.LineDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ODEInt.LineDouble___nonzero__(self)

    def __bool__(self):
        return _ODEInt.LineDouble___bool__(self)

    def __len__(self):
        return _ODEInt.LineDouble___len__(self)

    def __getslice__(self, i, j):
        return _ODEInt.LineDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ODEInt.LineDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ODEInt.LineDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ODEInt.LineDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ODEInt.LineDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ODEInt.LineDouble___setitem__(self, *args)

    def pop(self):
        return _ODEInt.LineDouble_pop(self)

    def append(self, x):
        return _ODEInt.LineDouble_append(self, x)

    def empty(self):
        return _ODEInt.LineDouble_empty(self)

    def size(self):
        return _ODEInt.LineDouble_size(self)

    def swap(self, v):
        return _ODEInt.LineDouble_swap(self, v)

    def begin(self):
        return _ODEInt.LineDouble_begin(self)

    def end(self):
        return _ODEInt.LineDouble_end(self)

    def rbegin(self):
        return _ODEInt.LineDouble_rbegin(self)

    def rend(self):
        return _ODEInt.LineDouble_rend(self)

    def clear(self):
        return _ODEInt.LineDouble_clear(self)

    def get_allocator(self):
        return _ODEInt.LineDouble_get_allocator(self)

    def pop_back(self):
        return _ODEInt.LineDouble_pop_back(self)

    def erase(self, *args):
        return _ODEInt.LineDouble_erase(self, *args)

    def __init__(self, *args):
        this = _ODEInt.new_LineDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _ODEInt.LineDouble_push_back(self, x)

    def front(self):
        return _ODEInt.LineDouble_front(self)

    def back(self):
        return _ODEInt.LineDouble_back(self)

    def assign(self, n, x):
        return _ODEInt.LineDouble_assign(self, n, x)

    def resize(self, *args):
        return _ODEInt.LineDouble_resize(self, *args)

    def insert(self, *args):
        return _ODEInt.LineDouble_insert(self, *args)

    def reserve(self, n):
        return _ODEInt.LineDouble_reserve(self, n)

    def capacity(self):
        return _ODEInt.LineDouble_capacity(self)
    __swig_destroy__ = _ODEInt.delete_LineDouble
    __del__ = lambda self: None
LineDouble_swigregister = _ODEInt.LineDouble_swigregister
LineDouble_swigregister(LineDouble)

class ArrayInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArrayInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArrayInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _ODEInt.ArrayInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ODEInt.ArrayInt___nonzero__(self)

    def __bool__(self):
        return _ODEInt.ArrayInt___bool__(self)

    def __len__(self):
        return _ODEInt.ArrayInt___len__(self)

    def __getslice__(self, i, j):
        return _ODEInt.ArrayInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ODEInt.ArrayInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ODEInt.ArrayInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ODEInt.ArrayInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ODEInt.ArrayInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ODEInt.ArrayInt___setitem__(self, *args)

    def pop(self):
        return _ODEInt.ArrayInt_pop(self)

    def append(self, x):
        return _ODEInt.ArrayInt_append(self, x)

    def empty(self):
        return _ODEInt.ArrayInt_empty(self)

    def size(self):
        return _ODEInt.ArrayInt_size(self)

    def swap(self, v):
        return _ODEInt.ArrayInt_swap(self, v)

    def begin(self):
        return _ODEInt.ArrayInt_begin(self)

    def end(self):
        return _ODEInt.ArrayInt_end(self)

    def rbegin(self):
        return _ODEInt.ArrayInt_rbegin(self)

    def rend(self):
        return _ODEInt.ArrayInt_rend(self)

    def clear(self):
        return _ODEInt.ArrayInt_clear(self)

    def get_allocator(self):
        return _ODEInt.ArrayInt_get_allocator(self)

    def pop_back(self):
        return _ODEInt.ArrayInt_pop_back(self)

    def erase(self, *args):
        return _ODEInt.ArrayInt_erase(self, *args)

    def __init__(self, *args):
        this = _ODEInt.new_ArrayInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _ODEInt.ArrayInt_push_back(self, x)

    def front(self):
        return _ODEInt.ArrayInt_front(self)

    def back(self):
        return _ODEInt.ArrayInt_back(self)

    def assign(self, n, x):
        return _ODEInt.ArrayInt_assign(self, n, x)

    def resize(self, *args):
        return _ODEInt.ArrayInt_resize(self, *args)

    def insert(self, *args):
        return _ODEInt.ArrayInt_insert(self, *args)

    def reserve(self, n):
        return _ODEInt.ArrayInt_reserve(self, n)

    def capacity(self):
        return _ODEInt.ArrayInt_capacity(self)
    __swig_destroy__ = _ODEInt.delete_ArrayInt
    __del__ = lambda self: None
ArrayInt_swigregister = _ODEInt.ArrayInt_swigregister
ArrayInt_swigregister(ArrayInt)

class ArrayDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArrayDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArrayDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _ODEInt.ArrayDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ODEInt.ArrayDouble___nonzero__(self)

    def __bool__(self):
        return _ODEInt.ArrayDouble___bool__(self)

    def __len__(self):
        return _ODEInt.ArrayDouble___len__(self)

    def __getslice__(self, i, j):
        return _ODEInt.ArrayDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ODEInt.ArrayDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ODEInt.ArrayDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ODEInt.ArrayDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ODEInt.ArrayDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ODEInt.ArrayDouble___setitem__(self, *args)

    def pop(self):
        return _ODEInt.ArrayDouble_pop(self)

    def append(self, x):
        return _ODEInt.ArrayDouble_append(self, x)

    def empty(self):
        return _ODEInt.ArrayDouble_empty(self)

    def size(self):
        return _ODEInt.ArrayDouble_size(self)

    def swap(self, v):
        return _ODEInt.ArrayDouble_swap(self, v)

    def begin(self):
        return _ODEInt.ArrayDouble_begin(self)

    def end(self):
        return _ODEInt.ArrayDouble_end(self)

    def rbegin(self):
        return _ODEInt.ArrayDouble_rbegin(self)

    def rend(self):
        return _ODEInt.ArrayDouble_rend(self)

    def clear(self):
        return _ODEInt.ArrayDouble_clear(self)

    def get_allocator(self):
        return _ODEInt.ArrayDouble_get_allocator(self)

    def pop_back(self):
        return _ODEInt.ArrayDouble_pop_back(self)

    def erase(self, *args):
        return _ODEInt.ArrayDouble_erase(self, *args)

    def __init__(self, *args):
        this = _ODEInt.new_ArrayDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _ODEInt.ArrayDouble_push_back(self, x)

    def front(self):
        return _ODEInt.ArrayDouble_front(self)

    def back(self):
        return _ODEInt.ArrayDouble_back(self)

    def assign(self, n, x):
        return _ODEInt.ArrayDouble_assign(self, n, x)

    def resize(self, *args):
        return _ODEInt.ArrayDouble_resize(self, *args)

    def insert(self, *args):
        return _ODEInt.ArrayDouble_insert(self, *args)

    def reserve(self, n):
        return _ODEInt.ArrayDouble_reserve(self, n)

    def capacity(self):
        return _ODEInt.ArrayDouble_capacity(self)
    __swig_destroy__ = _ODEInt.delete_ArrayDouble
    __del__ = lambda self: None
ArrayDouble_swigregister = _ODEInt.ArrayDouble_swigregister
ArrayDouble_swigregister(ArrayDouble)

class Solution(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Solution, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Solution, name)
    __repr__ = _swig_repr
    __swig_setmethods__["t"] = _ODEInt.Solution_t_set
    __swig_getmethods__["t"] = _ODEInt.Solution_t_get
    if _newclass:
        t = _swig_property(_ODEInt.Solution_t_get, _ODEInt.Solution_t_set)
    __swig_setmethods__["y"] = _ODEInt.Solution_y_set
    __swig_getmethods__["y"] = _ODEInt.Solution_y_get
    if _newclass:
        y = _swig_property(_ODEInt.Solution_y_get, _ODEInt.Solution_y_set)

    def __init__(self):
        this = _ODEInt.new_Solution()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ODEInt.delete_Solution
    __del__ = lambda self: None
Solution_swigregister = _ODEInt.Solution_swigregister
Solution_swigregister(Solution)

class ODEClass_Test(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ODEClass_Test, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ODEClass_Test, name)
    __repr__ = _swig_repr

    def compute_ODE(self, TBnds, dim, RelTolm, AbsTol, mu):
        return _ODEInt.ODEClass_Test_compute_ODE(self, TBnds, dim, RelTolm, AbsTol, mu)

    def __init__(self):
        this = _ODEInt.new_ODEClass_Test()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ODEInt.delete_ODEClass_Test
    __del__ = lambda self: None
ODEClass_Test_swigregister = _ODEInt.ODEClass_Test_swigregister
ODEClass_Test_swigregister(ODEClass_Test)

# This file is compatible with both classic and new-style classes.


