# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_InterpTest')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_InterpTest')
    _InterpTest = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_InterpTest', [dirname(__file__)])
        except ImportError:
            import _InterpTest
            return _InterpTest
        try:
            _mod = imp.load_module('_InterpTest', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _InterpTest = swig_import_helper()
    del swig_import_helper
else:
    import _InterpTest
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _InterpTest.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _InterpTest.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _InterpTest.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _InterpTest.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _InterpTest.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _InterpTest.SwigPyIterator_equal(self, x)

    def copy(self):
        return _InterpTest.SwigPyIterator_copy(self)

    def next(self):
        return _InterpTest.SwigPyIterator_next(self)

    def __next__(self):
        return _InterpTest.SwigPyIterator___next__(self)

    def previous(self):
        return _InterpTest.SwigPyIterator_previous(self)

    def advance(self, n):
        return _InterpTest.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _InterpTest.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _InterpTest.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _InterpTest.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _InterpTest.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _InterpTest.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _InterpTest.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _InterpTest.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class LineInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LineInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LineInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _InterpTest.LineInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _InterpTest.LineInt___nonzero__(self)

    def __bool__(self):
        return _InterpTest.LineInt___bool__(self)

    def __len__(self):
        return _InterpTest.LineInt___len__(self)

    def __getslice__(self, i, j):
        return _InterpTest.LineInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _InterpTest.LineInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _InterpTest.LineInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _InterpTest.LineInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _InterpTest.LineInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _InterpTest.LineInt___setitem__(self, *args)

    def pop(self):
        return _InterpTest.LineInt_pop(self)

    def append(self, x):
        return _InterpTest.LineInt_append(self, x)

    def empty(self):
        return _InterpTest.LineInt_empty(self)

    def size(self):
        return _InterpTest.LineInt_size(self)

    def swap(self, v):
        return _InterpTest.LineInt_swap(self, v)

    def begin(self):
        return _InterpTest.LineInt_begin(self)

    def end(self):
        return _InterpTest.LineInt_end(self)

    def rbegin(self):
        return _InterpTest.LineInt_rbegin(self)

    def rend(self):
        return _InterpTest.LineInt_rend(self)

    def clear(self):
        return _InterpTest.LineInt_clear(self)

    def get_allocator(self):
        return _InterpTest.LineInt_get_allocator(self)

    def pop_back(self):
        return _InterpTest.LineInt_pop_back(self)

    def erase(self, *args):
        return _InterpTest.LineInt_erase(self, *args)

    def __init__(self, *args):
        this = _InterpTest.new_LineInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _InterpTest.LineInt_push_back(self, x)

    def front(self):
        return _InterpTest.LineInt_front(self)

    def back(self):
        return _InterpTest.LineInt_back(self)

    def assign(self, n, x):
        return _InterpTest.LineInt_assign(self, n, x)

    def resize(self, *args):
        return _InterpTest.LineInt_resize(self, *args)

    def insert(self, *args):
        return _InterpTest.LineInt_insert(self, *args)

    def reserve(self, n):
        return _InterpTest.LineInt_reserve(self, n)

    def capacity(self):
        return _InterpTest.LineInt_capacity(self)
    __swig_destroy__ = _InterpTest.delete_LineInt
    __del__ = lambda self: None
LineInt_swigregister = _InterpTest.LineInt_swigregister
LineInt_swigregister(LineInt)

class LineDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LineDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LineDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _InterpTest.LineDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _InterpTest.LineDouble___nonzero__(self)

    def __bool__(self):
        return _InterpTest.LineDouble___bool__(self)

    def __len__(self):
        return _InterpTest.LineDouble___len__(self)

    def __getslice__(self, i, j):
        return _InterpTest.LineDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _InterpTest.LineDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _InterpTest.LineDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _InterpTest.LineDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _InterpTest.LineDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _InterpTest.LineDouble___setitem__(self, *args)

    def pop(self):
        return _InterpTest.LineDouble_pop(self)

    def append(self, x):
        return _InterpTest.LineDouble_append(self, x)

    def empty(self):
        return _InterpTest.LineDouble_empty(self)

    def size(self):
        return _InterpTest.LineDouble_size(self)

    def swap(self, v):
        return _InterpTest.LineDouble_swap(self, v)

    def begin(self):
        return _InterpTest.LineDouble_begin(self)

    def end(self):
        return _InterpTest.LineDouble_end(self)

    def rbegin(self):
        return _InterpTest.LineDouble_rbegin(self)

    def rend(self):
        return _InterpTest.LineDouble_rend(self)

    def clear(self):
        return _InterpTest.LineDouble_clear(self)

    def get_allocator(self):
        return _InterpTest.LineDouble_get_allocator(self)

    def pop_back(self):
        return _InterpTest.LineDouble_pop_back(self)

    def erase(self, *args):
        return _InterpTest.LineDouble_erase(self, *args)

    def __init__(self, *args):
        this = _InterpTest.new_LineDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _InterpTest.LineDouble_push_back(self, x)

    def front(self):
        return _InterpTest.LineDouble_front(self)

    def back(self):
        return _InterpTest.LineDouble_back(self)

    def assign(self, n, x):
        return _InterpTest.LineDouble_assign(self, n, x)

    def resize(self, *args):
        return _InterpTest.LineDouble_resize(self, *args)

    def insert(self, *args):
        return _InterpTest.LineDouble_insert(self, *args)

    def reserve(self, n):
        return _InterpTest.LineDouble_reserve(self, n)

    def capacity(self):
        return _InterpTest.LineDouble_capacity(self)
    __swig_destroy__ = _InterpTest.delete_LineDouble
    __del__ = lambda self: None
LineDouble_swigregister = _InterpTest.LineDouble_swigregister
LineDouble_swigregister(LineDouble)

class ArrayInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArrayInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArrayInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _InterpTest.ArrayInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _InterpTest.ArrayInt___nonzero__(self)

    def __bool__(self):
        return _InterpTest.ArrayInt___bool__(self)

    def __len__(self):
        return _InterpTest.ArrayInt___len__(self)

    def __getslice__(self, i, j):
        return _InterpTest.ArrayInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _InterpTest.ArrayInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _InterpTest.ArrayInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _InterpTest.ArrayInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _InterpTest.ArrayInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _InterpTest.ArrayInt___setitem__(self, *args)

    def pop(self):
        return _InterpTest.ArrayInt_pop(self)

    def append(self, x):
        return _InterpTest.ArrayInt_append(self, x)

    def empty(self):
        return _InterpTest.ArrayInt_empty(self)

    def size(self):
        return _InterpTest.ArrayInt_size(self)

    def swap(self, v):
        return _InterpTest.ArrayInt_swap(self, v)

    def begin(self):
        return _InterpTest.ArrayInt_begin(self)

    def end(self):
        return _InterpTest.ArrayInt_end(self)

    def rbegin(self):
        return _InterpTest.ArrayInt_rbegin(self)

    def rend(self):
        return _InterpTest.ArrayInt_rend(self)

    def clear(self):
        return _InterpTest.ArrayInt_clear(self)

    def get_allocator(self):
        return _InterpTest.ArrayInt_get_allocator(self)

    def pop_back(self):
        return _InterpTest.ArrayInt_pop_back(self)

    def erase(self, *args):
        return _InterpTest.ArrayInt_erase(self, *args)

    def __init__(self, *args):
        this = _InterpTest.new_ArrayInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _InterpTest.ArrayInt_push_back(self, x)

    def front(self):
        return _InterpTest.ArrayInt_front(self)

    def back(self):
        return _InterpTest.ArrayInt_back(self)

    def assign(self, n, x):
        return _InterpTest.ArrayInt_assign(self, n, x)

    def resize(self, *args):
        return _InterpTest.ArrayInt_resize(self, *args)

    def insert(self, *args):
        return _InterpTest.ArrayInt_insert(self, *args)

    def reserve(self, n):
        return _InterpTest.ArrayInt_reserve(self, n)

    def capacity(self):
        return _InterpTest.ArrayInt_capacity(self)
    __swig_destroy__ = _InterpTest.delete_ArrayInt
    __del__ = lambda self: None
ArrayInt_swigregister = _InterpTest.ArrayInt_swigregister
ArrayInt_swigregister(ArrayInt)

class ArrayDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ArrayDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ArrayDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _InterpTest.ArrayDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _InterpTest.ArrayDouble___nonzero__(self)

    def __bool__(self):
        return _InterpTest.ArrayDouble___bool__(self)

    def __len__(self):
        return _InterpTest.ArrayDouble___len__(self)

    def __getslice__(self, i, j):
        return _InterpTest.ArrayDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _InterpTest.ArrayDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _InterpTest.ArrayDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _InterpTest.ArrayDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _InterpTest.ArrayDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _InterpTest.ArrayDouble___setitem__(self, *args)

    def pop(self):
        return _InterpTest.ArrayDouble_pop(self)

    def append(self, x):
        return _InterpTest.ArrayDouble_append(self, x)

    def empty(self):
        return _InterpTest.ArrayDouble_empty(self)

    def size(self):
        return _InterpTest.ArrayDouble_size(self)

    def swap(self, v):
        return _InterpTest.ArrayDouble_swap(self, v)

    def begin(self):
        return _InterpTest.ArrayDouble_begin(self)

    def end(self):
        return _InterpTest.ArrayDouble_end(self)

    def rbegin(self):
        return _InterpTest.ArrayDouble_rbegin(self)

    def rend(self):
        return _InterpTest.ArrayDouble_rend(self)

    def clear(self):
        return _InterpTest.ArrayDouble_clear(self)

    def get_allocator(self):
        return _InterpTest.ArrayDouble_get_allocator(self)

    def pop_back(self):
        return _InterpTest.ArrayDouble_pop_back(self)

    def erase(self, *args):
        return _InterpTest.ArrayDouble_erase(self, *args)

    def __init__(self, *args):
        this = _InterpTest.new_ArrayDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _InterpTest.ArrayDouble_push_back(self, x)

    def front(self):
        return _InterpTest.ArrayDouble_front(self)

    def back(self):
        return _InterpTest.ArrayDouble_back(self)

    def assign(self, n, x):
        return _InterpTest.ArrayDouble_assign(self, n, x)

    def resize(self, *args):
        return _InterpTest.ArrayDouble_resize(self, *args)

    def insert(self, *args):
        return _InterpTest.ArrayDouble_insert(self, *args)

    def reserve(self, n):
        return _InterpTest.ArrayDouble_reserve(self, n)

    def capacity(self):
        return _InterpTest.ArrayDouble_capacity(self)
    __swig_destroy__ = _InterpTest.delete_ArrayDouble
    __del__ = lambda self: None
ArrayDouble_swigregister = _InterpTest.ArrayDouble_swigregister
ArrayDouble_swigregister(ArrayDouble)

class Data(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Data, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Data, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _InterpTest.Data_x_set
    __swig_getmethods__["x"] = _InterpTest.Data_x_get
    if _newclass:
        x = _swig_property(_InterpTest.Data_x_get, _InterpTest.Data_x_set)
    __swig_setmethods__["y"] = _InterpTest.Data_y_set
    __swig_getmethods__["y"] = _InterpTest.Data_y_get
    if _newclass:
        y = _swig_property(_InterpTest.Data_y_get, _InterpTest.Data_y_set)
    __swig_setmethods__["y_p"] = _InterpTest.Data_y_p_set
    __swig_getmethods__["y_p"] = _InterpTest.Data_y_p_get
    if _newclass:
        y_p = _swig_property(_InterpTest.Data_y_p_get, _InterpTest.Data_y_p_set)

    def __init__(self):
        this = _InterpTest.new_Data()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _InterpTest.delete_Data
    __del__ = lambda self: None
Data_swigregister = _InterpTest.Data_swigregister
Data_swigregister(Data)

class Test(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Test, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Test, name)
    __repr__ = _swig_repr
    __swig_setmethods__["size"] = _InterpTest.Test_size_set
    __swig_getmethods__["size"] = _InterpTest.Test_size_get
    if _newclass:
        size = _swig_property(_InterpTest.Test_size_get, _InterpTest.Test_size_set)
    __swig_setmethods__["method"] = _InterpTest.Test_method_set
    __swig_getmethods__["method"] = _InterpTest.Test_method_get
    if _newclass:
        method = _swig_property(_InterpTest.Test_method_get, _InterpTest.Test_method_set)

    def __init__(self):
        this = _InterpTest.new_Test()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _InterpTest.delete_Test
    __del__ = lambda self: None
Test_swigregister = _InterpTest.Test_swigregister
Test_swigregister(Test)

class InterpClass_Test(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, InterpClass_Test, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, InterpClass_Test, name)
    __repr__ = _swig_repr

    def set_xy(self, size, Bnds):
        return _InterpTest.InterpClass_Test_set_xy(self, size, Bnds)

    def get_spline(self, mydata):
        return _InterpTest.InterpClass_Test_get_spline(self, mydata)

    def eval_spline(self, MySpline, ScatterData, size, flag):
        return _InterpTest.InterpClass_Test_eval_spline(self, MySpline, ScatterData, size, flag)

    def integrate_spline(self, MySpline, ScatterData, size):
        return _InterpTest.InterpClass_Test_integrate_spline(self, MySpline, ScatterData, size)

    def __init__(self):
        this = _InterpTest.new_InterpClass_Test()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _InterpTest.delete_InterpClass_Test
    __del__ = lambda self: None
InterpClass_Test_swigregister = _InterpTest.InterpClass_Test_swigregister
InterpClass_Test_swigregister(InterpClass_Test)

# This file is compatible with both classic and new-style classes.


